sonar.organization=abiliogamanetoj
sonar.projectKey=AbilioGamaNetoJ_restaurante-rei-picadao
sonar.projectName=Rei do Picadao
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src,e2e
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.exclusions=**/*.test.ts,**/*.spec.ts,**/node_modules/**,**/.next/**,**/drizzle/**
sonar.typescript.node=node
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.config.*,src/db/**,src/app/**/*.tsx,e2e/**,**/*.test.ts
